version: '3'
services:
  view:
    build: ./view
    command: bash -c "npm i && npm start"
    volumes:
      - ./view:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
  view-api:
    build: ./view-api
    command: bash -c "npm i && npm run dev"
    volumes:
      - ./view-api:/usr/app/
      - /usr/app/node_modules
    ports:
      - 4000:4000
